version: "3"
services:
    node-app:
        build: .
        ports:
            - "3030:4000"
        env_file:
            - ./.env
        depends_on:
            - mongo

    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=degerbeger
            - MONGO_INITDB_ROOT_PASSWORD=mypassword
        volumes:
            - mongo-db:/data/db

volumes:
    mongo-db: