version: "3"
services:
    node-app:
        build: .
        ports:
            - "3030:4000"
        volumes:
            - ./:/app
            - /app/node_modules
        env_file:
            - ./.env
        # environment:
        #     PORT=3000